development:
  sessions:
    default:
      username: user
      password: password
      database: rails_base_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      username: user
      password: password
      database: rails_base_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
    options:
      scope_overwrite_exception: true
      raise_not_found_error: false
      use_activesupport_time_zone: false
      use_utc: true

